---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-ws-external-db
  labels:
    app: gdit-digitus-ws-external-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-ws-external-db
  template:
    metadata:
      labels:
        app: gdit-digitus-ws-external-db
    spec:
      containers:
      - name: gdit-digitus-ws-external-db
        imagePullPolicy: Always
        image: 172.31.15.195/gdit-digitus-ws-external-db:develop
        ports:
        - containerPort: 8082
        envFrom:
          - configMapRef:
              name: digitus-configmap
          - secretRef:
              name: digitus-secrets
