apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-ws-persistence-bioanalisis
  labels:
    app: gdit-digitus-ws-persistence-bioanalisis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-ws-persistence-bioanalisis
  template:
    metadata:
      labels:
        app: gdit-digitus-ws-persistence-bioanalisis
    spec:
      containers:
      - name: gdit-digitus-ws-persistence-bioanalisis
        imagePullPolicy: Always
        image: 172.31.15.195/gdit-digitus-ws-persistence-bioanalisis:develop
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: digitus-configmap
          - secretRef:
              name: digitus-secrets
