---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-esb-gluster-stakeholders
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: digitus/services/gluster/stakeholders
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-esb-gluster-stakeholders
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
