apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-jms-external-response
  labels:
    app: gdit-digitus-jms-external-response
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-jms-external-response
  template:
    metadata:
      labels:
        app: gdit-digitus-jms-external-response
    spec:
      containers:
        - name: gdit-digitus-jms-external-response
          imagePullPolicy: Always
          image: cicd-pipeline.services.digitus/gdit-digitus-jms-external-response:develop
          env:
            - name: "ACTIVEMQ_URL"
              value: "tcp://gdit-digitus-service-activemq:61616"
            - name: "MONGO_REST_URL"
              value: "http://gdit-digitus-ws-mongodb:8080/digitusJson/"
            - name: "EXTERNAL_DB_URL"
              value: "http://gdit-digitus-ws-external-db:8082/ws-digitus-external-db/digitus/"
            # - name: "GLUSTERFS_REST_URL"
              # value: "http://gdit-digitus-esb-gluster:8075/ws-rest-gluster/digitus-upload"
            - name: "GLUSTERFS_REST_URL"
              value: "http://172.31.0.102:30891/ws-rest-gluster/digitus-upload"
            - name: "TZ"
              value: "America/Mexico_City"
          ports:
            - containerPort: 8079
