apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-esb-external-search
  labels:
    app: gdit-digitus-esb-external-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-esb-external-search
  template:
    metadata:
      labels:
        app: gdit-digitus-esb-external-search
    spec:
      containers:
        - name: gdit-digitus-esb-external-search
          imagePullPolicy: Always
          image: cicd-pipeline.services.digitus/gdit-digitus-esb-external-search:develop
          env:
            - name: "EXTERNAL_DB_URL"
              value: "http://gdit-digitus-ws-external-db:8082/ws-digitus-external-db/digitus/"
            - name: "GLUSTERFS_REST_URL"
              value: "http://172.31.0.102:30891/ws-rest-gluster/digitus-upload"
            - name: "API_CEPH_HOST"
              value: "gdit-digitus-ws-ceph-storage"
            - name: "API_CEPH_PORT"
              value: "8080"
            - name: "API_DB_HOST"
              value: "gdit-digitus-ws-external-db"
            - name: "API_DB_PORT"
              value: "8082"
            - name: "API_IDC_HOST"
              value: "gdit-digitus-ws-idc-validation"
            - name: "API_IDC_PORT"
              value: "8080"
            - name: "ACTIVEMQ_URL"
              value: "tcp://gdit-digitus-service-activemq:61616"
            - name: "ACTIVEMQ_IP"
              value: "gdit-digitus-service-activemq"
            - name: "ACTIVEMQ_HOST"
              value: "gdit-digitus-service-activemq"
            - name: "ACTIVEMQ_PORT"
              value: "61616"
            - name: "ACTIVEMQ_QUEUE"
              value: "external-search-request"
            - name: "ACTIVEMQ_PASSWORD"
              value: "admin"
            - name: "ACTIVEMQ_USER"
              value: "admin"
            - name: "TZ"
              value: "America/Mexico_City"
            - name: "CAMEL_PORT"
              value: "8085"
            - name: "KIE_PROJECT"
              value: "RulesProjects"
            - name: "KIE_SESSION_NAME"
              value: "KieSession"
            - name: "KIE_AUTHORIZATION"
              value: "a2llc2VydmVyOmtpZXNlcnZlcjEh"
            - name: "KIE_SERVERURL"
              value: "http://gdit-digitus-service-jbpm:8080/kie-server/services/rest/server"
          ports:
            - containerPort: 8085
