apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-esb-gluster
  labels:
    app: gdit-digitus-esb-gluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-esb-gluster
  template:
    metadata:
      labels:
        app: gdit-digitus-esb-gluster
    spec:
      containers:
        - name: gdit-digitus-esb-gluster
          imagePullPolicy: Always
          image: cicd-pipeline.services.digitus/esb-digitus-gluster:0.0.3
          env:
          - name: "TZ"
            value: "America/Mexico_City"
          ports:
            - containerPort: 8075
          volumeMounts:
            - name: dev-pv-esb-gluster
              mountPath: "/home/gluster/stakeholders/"
      volumes:
      - name: dev-pv-esb-gluster
        persistentVolumeClaim:
          claimName: dev-pvc-esb-gluster
