apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-service-postgresql
  labels:
    app: gdit-digitus-service-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-service-postgresql
  template:
    metadata:
      labels:
        app: gdit-digitus-service-postgresql
    spec:
      containers:
      - name: gdit-digitus-service-postgresql
        imagePullPolicy: Always
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: gdit-digitus-configmap
          - secretRef:
              name: gdit-digitus-secrets
        volumeMounts:
        - name: pv-service-postgresql-data
          mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: pv-service-postgresql-data
        persistentVolumeClaim:
          claimName: pvc-service-postgresql-data
