apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-service-openldap
  labels:
    app: gdit-digitus-service-openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-service-openldap
  template:
    metadata:
      labels:
        app: gdit-digitus-service-openldap
    spec:
      containers:
        - name: gdit-digitus-service-openldap
          imagePullPolicy: Always
          image: 172.31.15.195/debian9-openldap:2.4.0
          envFrom:
            - configMapRef:
                name: digitus-configmap
            - secretRef:
                name: digitus-secrets
          ports:
            - containerPort: 389
            - containerPort: 636
          volumeMounts:
            - name: pv-service-openldap-slapd
              mountPath: "/etc/ldap/slapd.d"
            - name: pv-service-openldap-ldap
              mountPath: "/var/lib/ldap"
      volumes:
      - name: pv-service-openldap-slapd
        persistentVolumeClaim:
          claimName: pvc-service-openldap-slapd
      - name: pv-service-openldap-ldap
        persistentVolumeClaim:
          claimName: pvc-service-openldap-ldap
