apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-service-jbpm
  labels:
    app: gdit-digitus-service-jbpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-service-jbpm
  template:
    metadata:
      labels:
        app: gdit-digitus-service-jbpm
    spec:
      containers:
      - name: gdit-digitus-service-jbpm
        image: 172.31.15.195/centos7-jbpm:7.34.0
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
          - containerPort: 8080
          - containerPort: 8001
            protocol: TCP
        envFrom:
          - configMapRef:
              name: digitus-configmap
          - secretRef:
              name: digitus-secrets
        volumeMounts:
         - name: pv-service-jbpm-niogit
           mountPath: "/opt/jboss/wildfly/bin/.niogit"
         - name: pv-service-jbpm-m2
           mountPath: "/opt/jboss/.m2"
      volumes:
      - name: pv-service-jbpm-niogit
        persistentVolumeClaim:
          claimName: pvc-service-jbpm-niogit
      - name: pv-service-jbpm-m2
        persistentVolumeClaim:
          claimName: pvc-service-jbpm-m2
