apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-service-sso
  labels:
    app: gdit-digitus-service-sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-service-sso
  template:
    metadata:
      labels:
        app: gdit-digitus-service-sso
    spec:
      containers:
        - name: gdit-digitus-service-sso
          imagePullPolicy: Always
          image: 172.31.15.195/rhel7-sso:7.3.5
          envFrom:
            - configMapRef:
                name: gdit-digitus-configmap
            - secretRef:
                name: gdit-digitus-secrets
          ports:
            - containerPort: 8443
            - containerPort: 9993
          volumeMounts:
            - name: pv-service-sso-standalone
              mountPath: "/opt/eap/standalone"
      volumes:
        - name: pv-service-sso-standalone
          persistentVolumeClaim:
            claimName: pvc-service-sso-standalone
