apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-esb-gluster
  labels:
    app: gdit-digitus-esb-gluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-esb-gluster
  template:
    metadata:
      labels:
        app: gdit-digitus-esb-gluster
    spec:
      containers:
        - name: gdit-digitus-esb-gluster
          imagePullPolicy: Always
          image: 172.31.15.195/gdit-digitus-esb-gluster:gto
          envFrom:
            - configMapRef:
                name: gdit-digitus-configmap
            - secretRef:
                name: gdit-digitus-secrets
          ports:
            - containerPort: 8075
          volumeMounts:
            - name: pv-esb-gluster-stakeholders
              mountPath: "/home/gluster/stakeholders/"
      volumes:
      - name: pv-esb-gluster-stakeholders
        persistentVolumeClaim:
          claimName: pvc-esb-gluster-stakeholders
