apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-ws-fusion
  labels:
    app: gdit-digitus-ws-fusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-ws-fusion
  template:
    metadata:
      labels:
        app: gdit-digitus-ws-fusion
    spec:
      containers:
      - name: gdit-digitus-ws-fusion
        imagePullPolicy: Always
        image: 172.31.15.195/gdit-digitus-ws-fusion:gto
        ports:
        - containerPort: 8081
        envFrom:
          - configMapRef:
              name: gdit-digitus-configmap
          - secretRef:
              name: gdit-digitus-secrets
