apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-ws-bmu
  labels:
    app: gdit-digitus-ws-bmu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-ws-bmu
  template:
    metadata:
      labels:
        app: gdit-digitus-ws-bmu
    spec:
      containers:
        - name: gdit-digitus-ws-idc-validation
          imagePullPolicy: Always
          image: 172.31.15.195/gdit-digitus-ws-bmu:gto
          ports:
            - containerPort: 8080
