apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-ws-idc-validation
  labels:
    app: gdit-digitus-ws-idc-validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-ws-idc-validation
  template:
    metadata:
      labels:
        app: gdit-digitus-ws-idc-validation
    spec:
      containers:
        - name: gdit-digitus-ws-idc-validation
          imagePullPolicy: Always
          image: 172.31.15.195/ws-idc-validation:gto
          envFrom:
            - configMapRef:
                name: gdit-digitus-configmap
            - secretRef:
                name: gdit-digitus-secrets
          ports:
            - containerPort: 8080
