apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-ws-idc-validation
  labels:
    app: gdit-digitus-ws-idc-validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-ws-idc-validation
  template:
    metadata:
      labels:
        app: gdit-digitus-ws-idc-validation
    spec:
      containers:
        - name: gdit-digitus-ws-idc-validation
          imagePullPolicy: Always
          image: cicd-pipeline.services.digitus/ws-idc-validation:0.0.12
          env:
            - name: "KIE_PROJECT_NAME"
              value: "RulesProjects"
            - name: "KIE_SERVERURL"
              value: "http://gdit-digitus-service-jbpm:8080/kie-server/services/rest/server"
            - name: "KIE_SESSION_NAME"
              value: "KieSession"
            - name: "KIE_PASSWORD"
              value: "wbadmin"
            - name: "KIE_USERNAME"
              value: "wbadmin"
            - name: "TZ"
              value: "America/Mexico_City"
          ports:
            - containerPort: 8080
