apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-ws-data-query
  labels:
    app: gdit-digitus-ws-data-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-ws-data-query
  template:
    metadata:
      labels:
        app: gdit-digitus-ws-data-query
    spec:
      containers:
        - name: gdit-digitus-ws-data-query
          imagePullPolicy: Always
          image: cicd-pipeline.services.digitus/gdit-digitus-ws-data-query:develop
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gdit-digitus-configmap
            - secretRef:
                name: gdit-digitus-secrets
