apiVersion: v1
kind: ConfigMap
metadata:
  name: gdit-digitus-configmap
data:
  TZ: "America/Mexico_City"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  # ACTIVEMQ
  ACTIVEMQ_CONFIG_NAME: "amqp-srv1"
  ACTIVEMQ_CONFIG_DEFAULTACCOUNT: "false"
  ACTIVEMQ_ADMIN_LOGIN: "admin"
  ACTIVEMQ_ADMIN_PASSWORD: "admin"
  ACTIVEMQ_USERS_myproducer: "producerpassword"
  ACTIVEMQ_GROUPS_writes: "myproducer"
  ACTIVEMQ_USERS_myconsumer: "consumerpassword"
  ACTIVEMQ_GROUPS_reads: "myconsumer"
  ACTIVEMQ_JMX_user1_role: "readwrite"
  ACTIVEMQ_JMX_user1_password: "jmx_password"
  ACTIVEMQ_JMX_user2_role: "read"
  ACTIVEMQ_JMX_user2_password: "jmx2_password"
  ACTIVEMQ_CONFIG_TOPICS_topic1: "mytopic1"
  ACTIVEMQ_CONFIG_TOPICS_topic2: "mytopic2"
  ACTIVEMQ_CONFIG_QUEUES_queue1: "myqueue1"
  ACTIVEMQ_CONFIG_QUEUES_queue2: "mytopic2"
  ACTIVEMQ_CONFIG_MINMEMORY: "1024"
  ACTIVEMQ_CONFIG_MAXMEMORY: "4096"
  ACTIVEMQ_CONFIG_SCHEDULERENABLED: "true"
  #LDAP
  LDAP_ORGANISATION: "Digitus"
  LDAP_DOMAIN: "digitus.com"
  LDAP_ADMIN_PASSWORD: "P@ss1W0Rd"
  LDAP_CONFIG_PASSWORD: "P@ss1W0Rd"
  LDAP_READONLY_USER: "true"
  LDAP_READONLY_USER_USERNAME: "ldap-ro"
  LDAP_READONLY_USER_PASSWORD: "P@ss1W0Rd"
