---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: dev-pv-ws-external-tx-certs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv23_develop/ws/gdit-digitus-ws-external-tx/certs
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-pvc-ws-external-tx-certs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
