apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdit-digitus-srv-bio-load-data
  labels:
    app: gdit-digitus-srv-bio-load-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdit-digitus-srv-bio-load-data
  template:
    metadata:
      labels:
        app: gdit-digitus-srv-bio-load-data
    spec:
      containers:
      - name: gdit-digitus-srv-bio-load-data
        imagePullPolicy: Always
        image: cicd-pipeline.services.digitus/srv_bio_load_data:develop 
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: digitus-configmap
          - secretRef:
              name: digitus-secrets

